### PR TITLE
man-db 2.7.6.1

### PR DESCRIPTION
**Pull request by bw-yuhogg**
Also, libpipeline 1.4.1

### CODE REVIEW

**Comment by bw-yuhogg** [comment]
https://travis-ci.org/Linuxbrew/homebrew-extra/builds/202501464#L2605
```
/bin/mkdir: cannot create directory `/usr/lib/tmpfiles.d': Permission denied
```

Uh-huh. Not sure what gives...

**Comment by sjackman** [comment]
Try `configure --with-systemdtmpfilesdir=#{prefix}/lib/tmpfiles.d`
Here's a comment in Makefile.am
```
# The default for systemdtmpfilesdir is intentionally not prefix-sensitive,
```

**Comment by bw-yuhogg** [comment]
https://travis-ci.org/Linuxbrew/homebrew-extra/builds/203077266#L2607-L2608
```
chown: changing ownership of `/home/linuxbrew/.linuxbrew/Cellar/man-db/2.7.6.1/bin/man': Operation not permitted

chown: changing ownership of `/home/linuxbrew/.linuxbrew/Cellar/man-db/2.7.6.1/bin/mandb': Operation not permitted
```

This is fun :)

**Comment by bw-yuhogg** [comment]
It was because the build system attempts to chown the `man` executable to `man:man`. Disabling setuid stops it from doing that.

**Comment by bw-yuhogg** [comment]
From Circle:
```
* Incorrect file permissions (664): chmod 644 /home/linuxbrew/.linuxbrew/Library/Taps/linuxbrew/homebrew-extra/Formula/libpipeline.rb
```

I'll submit a separate PR to fix that.

**Comment by bw-yuhogg** [comment]
Submitted as #7, but I've also cherry-picked it onto this branch to confirm it works.

**Comment by bw-yuhogg** [comment]
There's something wrong with the Travis webhook, but the build itself succeeded.

**Pull request closed without merging**
