### PR TITLE
Delete libpipeline.rb and man-db.rb

### PR DESCRIPTION
**Pull request by maxim-belkin**
Moving libpipeline to Homebrew/homebrew-core
See Homebrew/homebrew-core#36629

### CODE REVIEW

**Comment by sjackman** [comment]
Could you please update this PR to also remove `man-db`?

**Comment by maxim-belkin** [comment]
`libpipeline` is now a resource in `man-db`

**Comment by sjackman** [comment]
Good to go once PR https://github.com/Homebrew/homebrew-core/pull/36629 is merged. Thanks, Maxim.

**Comment by sjackman** [comment]
Once `man-db` is merged into Linuxbrew/core, we can merge this PR.
I'm not sure why CI is failing.

**Pull request merged**
