### PR TITLE
Use linuxbrew/brew not linuxbrew/linuxbrew Docker image on CircleCI

### PR DESCRIPTION
**Pull request by issyl0**
- Requested in #49.

### CODE REVIEW

**Review by sjackman — APPROVED** [review]
Thanks, Issy!

**Comment by sjackman** [comment]
Azure needs fixing too:
https://github.com/Linuxbrew/homebrew-extra/blob/0a5fc2e9c2a56843841308e3cfad2dc876e05b1f/azure-pipelines.yml#L17
Change https://github.com/Linuxbrew/brew to https://github.com/Homebrew/brew
In this PR or a new PR is fine.

**Comment by maxim-belkin** [comment]
What do you guys use Azure for? Shall I add it to the Xorg tap?

**Comment by sjackman** [comment]
The ultimate plan is to migrate from CircleCI to Azure for building bottles. We're not there yet, but making progress. See https://github.com/Homebrew/brew/issues/6255

**Comment by sjackman** [comment]
> Shall I add it to the Xorg tap?

Sure, if you like. Go for it. I mean need to enable it for you on Azure. I can take a look this afternoon. Let me know if you want to do this.

**Pull request merged**
