### PR TITLE
libunwind 1.2.1

### PR DESCRIPTION
**Pull request by maxim-belkin**
New formula

### CODE REVIEW

**Comment by sjackman** [comment]
`libunwind` was removed in https://github.com/Linuxbrew/homebrew-core/commit/a5f659736646d8db2d36939fcacd3d4dcbaa087b.
See related PRs https://github.com/Linuxbrew/homebrew-core/pull/7201 and https://github.com/Linuxbrew/homebrew-core/pull/7265.

What's your use case to add this formula?

**Comment by maxim-belkin** [comment]
This is an optional dependency of mesa.

**Comment by sjackman** [comment]
I suggest removing optional dependencies. See https://github.com/Homebrew/homebrew-core/issues/31510#issue-354224230

**Comment by maxim-belkin** [comment]
My reading of that discussion is that if dependency is useful, it should be made a normal dependency, and not an optional (whether through :recommended or :optional) one.

**Comment by sjackman** [comment]
Yep. I'd be inclined to remove `libunwind` from `mesa`.

**Comment by issyl0** [comment]
Hi @maxim-belkin! As you've probably seen from the activity in Homebrew/linuxbrew-core, we're moving away from Linux-only formulae being in this repo. This is for discoverability reasons.

This PR has been open for just under a year and is tagged with "do not merge". I'm going to close this, but if you still need this formula and the optional dependency removal question hasn't been resolved, please submit to Homebrew/linuxbrew-core.

Thanks!

**Pull request closed without merging**
