### PR TITLE
libpipeline 1.5.0

### PR DESCRIPTION
**Pull request by maxim-belkin**
New `libpipeline` that is required by new `man-db`

### CODE REVIEW

**Review by sjackman — APPROVED** [review]

**Comment by sjackman** [comment]
Thanks, Maxim!

**Comment by maxim-belkin** [comment]
can't pull the bottle :/

**Comment by sjackman** [comment]
CircleCI hasn't built a bottle.
See https://circleci.com/gh/Linuxbrew/homebrew-extra/113 then select `Artifacts` and expand `bottles/`

**Comment by sjackman** [comment]
TravisCI did build a bottle: https://travis-ci.org/Linuxbrew/homebrew-extra/builds/356925981

**Comment by sjackman** [comment]
This looks odd to me:
```
==> Tapping linuxbrew/extra
git clone https://github.com/Linuxbrew/homebrew-extra /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-extra --config core.autocrlf=false
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-extra'...
remote: Counting objects: 207, done.        
remote: Total 207 (delta 0), reused 0 (delta 0), pack-reused 207        
Receiving objects: 100% (207/207), 33.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (116/116), done.
Checking connectivity... done.
Tapped 5 formulae (35 files, 155.9KB)
```
https://circleci.com/gh/Linuxbrew/homebrew-extra/113
Linuxbrew/extra should already be tapped. I think this is the problem.

I can't say why, but I'd guess that this line isn't working as expected:
```sh
mkdir -p /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/$CIRCLE_PROJECT_USERNAME
cp -a . /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
```

**Comment by maxim-belkin** [comment]
Circle creates directories that don't exist (no need for mkdir)

Shall we update it according to the config in `xorg`?

**Comment by sjackman** [comment]
> Circle creates directories that don't exist (no need for mkdir)

`cp -a` does not create the necessary directory if it's missing. `git clone` does.

> Shall we update it according to the config in xorg?

I'd suggest figuring out why it's not working as expected first.

Adding…
```
echo /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
ls /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/$CIRCLE_PROJECT_USERNAME
ls /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
```
before and after the copy may help troubleshoot.

**Comment by maxim-belkin** [comment]
On Circle:
1. There are two folders "Linuxbrew" and "linuxbrew" under `~/.linuxbrew/Homebrew/Library/Taps`
2.
```
$ grep tar.gz  Linuxbrew/homebrew-extra/Formula/libpipeline.rb 
  url "https://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.4.2.tar.gz"

$ grep tar.gz  linuxbrew/homebrew-extra/Formula/libpipeline.rb 
  url "https://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.4.2.tar.gz"

$ grep tar.gz  ~/project/Formula/libpipeline.rb 
  url "https://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.5.0.tar.gz"
```

**Comment by maxim-belkin** [comment]
woo-hoo
```
Container 0

    bottles/
        brew-test-bot.xml
        libpipeline-1.5.0.x86_64_linux.bottle.json
        libpipeline-1.5.0.x86_64_linux.bottle.tar.gz
```

**Pull request closed without merging**
