### PR TITLE
minishift 1.1.0

### PR DESCRIPTION
**Pull request by gastaldi**
# Contributing to homebrew-extra:

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/homebrew-extra/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/homebrew-xorg/pulls) for the same update/change?
- [X] Does your submission pass
`brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Have you built your formula locally prior to submission with `brew install <formula>`?

**Important:  Depends on https://github.com/Homebrew/homebrew-core/pull/14819**

### CODE REVIEW

**Comment by gastaldi** [comment]
This needs to replace the minishift.rb formula in homebrew-core. Is this the correct repository?

**Comment by maxim-belkin** [comment]
Minishift is not Linux-only, or is it?

**Comment by gastaldi** [comment]
The binary referenced in the formula is Linux-only. Minishift runs on macOS (Darwin), Linux and Windows

**Comment by maxim-belkin** [comment]
This repo is for software that has no macOS ports. I'll let @sjackman and @rwhogg to chime in :)

**Comment by gastaldi** [comment]
@maxim-belkin thanks, looks like I need to open in the homebrew-core repo instead. I was unsure if this would fit the "dependencies on other formulas" scenario

**Comment by bw-yuhogg** [comment]
Unfortunately, I don't think this is likely to be accepted by Homebrew/homebrew-core. `minishift` is already available as a Cask.

I think it's reasonable to accept formulae here for which a Cask already exists, including `minishift` and similar formulae like `minikube`. I'm curious what @sjackman's opinion on this is.

**Comment by gastaldi** [comment]
IMHO I think `minishift` should be available as a Formula, since it does not have any GUI to be a Cask. The perfect approach would be to delete the Cask file, but I am not sure if that is allowed

**Comment by sjackman** [comment]
Superseded by https://github.com/Linuxbrew/homebrew-core/pull/3011
and https://github.com/Homebrew/homebrew-core/pull/14819

**Pull request closed without merging**
