### PR TITLE
linux-pam: new formula

### PR DESCRIPTION
**Pull request by maxim-belkin**
Moved from Linuxbrew/homebrew-core#1186

### CODE REVIEW

**Comment by sjackman** [comment]
Looks good to me. Just fix the weird return status of the test. Is there a `--help` or `--version` option?
```
==> /home/linuxbrew/.linuxbrew/Cellar/linux-pam/1.3.0/sbin/mkhomedir_helper
Usage: /home/linuxbrew/.linuxbrew/Cellar/linux-pam/1.3.0/sbin/mkhomedir_helper <username> [<umask> [<skeldir>]]
Error: linuxbrew/extra/linux-pam: failed
<0> expected but was
<14>.
==> FAILED
```
https://circleci.com/gh/Linuxbrew/homebrew-extra/6

**Comment by maxim-belkin** [comment]
Yes, the return code is `14`. If we specify username, it's `8`. I think we can't execute any of the files from `sbin` folder. There is, however, `upperLOWER` file buried under `lib/security/pam_filter/upperLOWER`.

**Comment by maxim-belkin** [comment]
Strangely enough, I was able to run this only once :/

**Comment by sjackman** [comment]
`14` is fine. Just change the test to
```ruby
assert_match "Usage", shell_output("#{sbin}/mkhomedir_helper", 14)
```

**Comment by sjackman** [comment]
```
==> /home/linuxbrew/.linuxbrew/Cellar/linux-pam/1.3.0/sbin/mkhomedir_helper
Usage: /home/linuxbrew/.linuxbrew/Cellar/linux-pam/1.3.0/sbin/mkhomedir_helper <username> [<umask> [<skeldir>]]
Error: linuxbrew/extra/linux-pam: failed
Expected /Usage/ to match "".
==> FAILED
```
Redirect stderr.
```ruby
assert_match "Usage", shell_output("#{sbin}/mkhomedir_helper 2>&1", 14)
```

**Review by sjackman — APPROVED** [review]

**Comment by sjackman** [comment]
:shipit:

**Comment by maxim-belkin** [comment]
I don't have permissions to push

**Comment by sjackman** [comment]
I fixed the GitHub permissions.

**Comment by sjackman** [comment]
@randy3k `linuxbrew/extra/linux-pam` is merged thanks to @maxim-belkin!

**Pull request closed without merging**
