### PR TITLE
lm_sensors 3-5-0

### PR DESCRIPTION
**Pull request by maxim-belkin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
For some reason brew produced incorrect name for the bottle...

**Comment by maxim-belkin** [comment]
@sjackman what shall we do about the bottle name/version? The version is 3.5.0 but because the file is called `.../V3-5-0` Brew thinks that the version is `5-0`. Shall I add `version "3.5.0"` to the formula?
https://bintray.com/beta/#/linuxbrew/bottles-extra/lm_sensors/5-0?tab=files

**Comment by sjackman** [comment]
Yes, please do add `version "3.5.0"`.

**Review by sjackman — APPROVED** [review]

**Comment by sjackman** [comment]
Thanks, Maxim! 🌟

**Pull request closed without merging**
