### PR TITLE
singularity 2.6.0 (new formula)

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
nice

**Comment by sjackman** [comment]
CircleCI
```
checking for python... no
configure: error: Please install python before installing.
```
https://circleci.com/gh/Linuxbrew/homebrew-extra/168

Unsure whether that's Python 2 or Python 3 that it wants.

**Comment by maxim-belkin** [comment]
depends_on `squashfs`

**Comment by maxim-belkin** [comment]
`python@2` is enough 
brew gist-logs singularity -> https://gist.github.com/126bec8cea652f7e645ac9f621beb3af

**Comment by maxim-belkin** [comment]
configure does not know ` --disable-debug`
I suggest adding
```
      "--with-mksquashfs=#{Formula["squashfs"].opt_bin}/mksquashfs",
      "--with-userns"
```

**Comment by sjackman** [comment]
Thanks for the tips, Maxim.

**Pull request closed without merging**
